[package]
name = "fleet-provider-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
base64 = "0.22.1"
fleet-application = { path = "../../fleet-application" }
fleet-core = { path = "../../fleet-core" }
serde_json = "1.0.151"

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.27.0"

