[package]
name = "fleet-provider-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
fleet-application = { path = "../../fleet-application" }
fleet-core = { path = "../../fleet-core" }

[lints]
workspace = true

