import { defineConfig } from 'orval';

// The drift check regenerates with this same configuration into a temporary
// directory and compares, so generation settings can never differ between the
// committed client and the one CI produces.
const target = process.env.FLEET_API_CLIENT_TARGET ?? './src/generated/fleet.ts';

export default defineConfig({
  fleet: {
    input: {
      target: './openapi.json',
    },
    output: {
      target,
      client: 'fetch',
      mode: 'single',
      clean: true,
      override: {
        header: (info) => [
          `Generated by orval from the Fleet Manager OpenAPI document (${info.title ?? 'Fleet Manager API'}).`,
          'Do not edit: run `pnpm --filter @frogbyte-io/fleet-api-client generate`.',
        ],
      },
    },
  },
});
