//! Versioned controller-to-node protocol types.
//!
//! This crate owns the wire contract of the outbound node channel described in
//! `docs/architecture/controller-node-protocol.md`: the frame envelope, version
//! negotiation, feature flags, explicit size limits, typed protocol faults, and
//! frozen golden fixtures.
//!
//! It contains no transport. Opening a connection, authenticating a node, and
//! executing commands belong to `fleetd` and the controller; this crate only
//! says what a frame is and whether one is acceptable.

#![warn(missing_docs)]

mod fault;
mod features;
pub mod fixtures;
mod frame;
mod limits;
mod version;

/// Types generated from `proto/fleet/node/v1/node.proto` at build time.
///
/// These are wire types. Treat them as the encoding boundary and keep domain
/// rules in the modules around them.
#[allow(
    clippy::all,
    clippy::pedantic,
    missing_docs,
    reason = "generated by prost from the protocol source"
)]
pub mod wire {
    include!(concat!(env!("OUT_DIR"), "/fleet.node.v1.rs"));
}

pub use fault::ProtocolFault;
pub use features::{canonical_feature_flags, negotiate_feature_flags};
pub use frame::{correlation_id, decode_frame, encode_frame, message_id};
pub use limits::{
    HEARTBEAT_INTERVAL_MILLIS, MAX_COMMAND_PAYLOAD_BYTES, MAX_FRAME_BYTES, MAX_IN_FLIGHT_COMMANDS,
    MAX_RESULT_PAYLOAD_BYTES, session_limits,
};
pub use version::{
    PROTOCOL_V1, ParseVersionRangeError, ProtocolVersion, SUPPORTED_PROTOCOL_VERSIONS,
    VersionRange, negotiate_protocol_version,
};
