[package]
name = "fleet-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
fleet-core = { path = "../fleet-core" }
serde = { version = "1.0.229", features = ["derive"] }
toml = { version = "0.9.7", features = ["parse"] }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.27.0"

