[package]
name = "fleet-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
fleet-core = { path = "../fleet-core" }
prost = "0.14.4"

[build-dependencies]
prost-build = "0.14.4"
protox = "0.9.1"

[dev-dependencies]
proptest = "1.11.0"

[lints]
workspace = true
